### ISSUE TITLE
priority poll - please participate!

### ISSUE THREAD

**Issue by zoechi** [bwu-dart-graveyard/core_elements#3]
Please let us know which elements are the most important for you to have.
Just add a response and list the names of the elements (highest prio first)

(The links point to the JavaScript core-elements doc and demo site if any and the last link refers the related task inside this repository)
- <a href="https://github.com/Polymer/core-action-icons">core-action-icons (GitHub repo)</a>
  (no docs) (no demo) #42
- ~~<a href="http://polymer.github.io/core-docs/#core-ajax">core-ajax (docs)</a>
  <a href="http://polymer.github.io/core-ajax/components/core-ajax/demo.html">(demo)</a> #4~~
- ~~core-bind (no docs) (no demo) #5~~
- ~~<a href="http://polymer.github.io/core-docs/#core-collapse">core-collapse (docs)</a>
  <a href="http://polymer.github.io/core-collapse/components/core-collapse/demo.html">(demo)</a> #6~~
- <a href="http://polymer.github.io/core-docs/#core-component-page">core-component-page (docs)</a>
  <a href="http://polymer.github.io/core-component-page/components/core-component-page/demo.html">(demo)</a> #43
- <a href="http://polymer.github.io/core-docs/#core-doc-viewer">core-doc-viewer (docs)</a>
  <a href="http://polymer.github.io/core-doc-viewer/components/core-doc-viewer/demo.html">(demo)</a> #7
- <a href="http://polymer.github.io/core-docs/#core-docs">core-docs (docs)</a> (no demo) #8
- core-drag-drop (no docs) (no demo) #9
- <a href="http://polymer.github.io/core-docs/#core-drawer-panel">core-drawer-panel (docs)</a>
  <a href="http://polymer.github.io/core-drawer-panel/components/core-drawer-panel/demo.html">(demo)</a> #10
- <a href="http://polymer.github.io/core-docs/#core-field">core-field (docs)</a>
  <a href="http://polymer.github.io/core-field/components/core-field/demo.html">(demo)</a> #11
- <a href="http://polymer.github.io/core-docs/#core-firebase">core-firebase (docs)</a>
  <a href="http://polymer.github.io/core-firebase/components/core-firebase/demo.html">(demo)</a> #12
- <a href="http://polymer.github.io/core-docs/#core-header-panel">core-header-panel (docs)</a>
  <a href="http://polymer.github.io/core-header-panel/components/core-header-panel/demo.html">(demo)</a> #13 
- <a href="http://polymer.github.io/core-docs/#core-icon">core-icon (docs)</a> 
  <a href="http://polymer.github.io/core-icon/components/core-icon/demo.html">(demo)</a> #15
- <a href="http://polymer.github.io/core-docs/#core-icon-button">core-icon-button (docs)</a>
  <a href="http://polymer.github.io/core-icon-button/components/core-icon-button/demo.html">(demo)</a> #14
- <a href="http://polymer.github.io/core-docs/#core-icons">core-icons (docs)</a> 
  <a href="http://polymer.github.io/core-icons/components/core-icons/demo.html">(demo)</a> #44
- <a href="http://polymer.github.io/core-docs/#core-iconsset">core-iconset (docs)</a> 
  <a href="http://polymer.github.io/core-iconset/components/core-iconset/demo.html">(demo)</a> #45
- <a href="http://polymer.github.io/core-docs/#core-iconsset-svg">core-iconset-svg (docs)</a> 
  <a href="http://polymer.github.io/core-iconset-svg/components/core-iconset-svg/demo.html">(demo)</a> #46
- <a href="http://polymer.github.io/core-docs/#core-input">core-input (docs)</a>
  <a href="http://polymer.github.io/core-input/components/core-input/demo.html">(demo)</a> #16
- <a href="http://polymer.github.io/core-docs/#core-item">core-item (docs)</a>
  <a href="http://polymer.github.io/core-item/components/core-item/demo.html">(demo)</a> #17
- <a href="http://polymer.github.io/core-docs/#core-layout">core-layout (docs)</a>
  <a href="http://polymer.github.io/core-layout/components/core-layout/demo.html">(demo)</a> #18
- ~~<a href="http://polymer.github.io/core-docs/#core-layout-grid">core-layout-grid (docs)</a>
  <a href="http://polymer.github.io/core-layout-grid/components/core-layout-grid/demo.html">(demo)</a> #19~~
- <a href="http://polymer.github.io/core-docs/#core-layout-trbl">core-layout-trbl (docs)</a>
  <a href="http://polymer.github.io/core-layout-trbl/components/core-layout-trbl/demo.html">(demo)</a> #20
- <a href="http://polymer.github.io/core-docs/#core-list">core-list (docs)</a>
  <a href="http://polymer.github.io/core-list/components/core-list/demo.html">(demo)</a> #21
- <a href="http://polymer.github.io/core-docs/#core-localstorage">core-localstorage (docs)</a>
  <a href="http://polymer.github.io/core-localstorage/components/core-localstorage/demo.html">(demo)</a> #22
- <a href="http://polymer.github.io/core-docs/#core-media-query">core-media-query (docs)</a>
  <a href="http://polymer.github.io/core-media-query/components/core-media-query/demo.html">(demo)</a> #23 
- <a href="http://polymer.github.io/core-docs/#core-menu">core-menu (docs)</a>
  <a href="http://polymer.github.io/core-menu/components/core-menu/demo.html">(demo)</a> #24
- <a href="http://polymer.github.io/core-docs/#core-menu-button">core-menu-button (docs)</a> (no demo) #25
- <a href="http://polymer.github.io/core-docs/#core-meta">core-meta (docs)</a>
  <a href="http://polymer.github.io/core-meta/components/core-meta/demo.html">(demo)</a> #26
- <a href="http://polymer.github.io/core-docs/#core-overlay">core-overlay (docs)</a>
  <a href="http://polymer.github.io/core-overlay/components/core-overlay/demo.html">(demo)</a> #27
- <a href="http://polymer.github.io/core-docs/#core-pages">core-pages (docs)</a>
  <a href="http://polymer.github.io/core-pages/components/core-pages/demo.html">(demo)</a> #28
- <a href="http://polymer.github.io/core-docs/#core-range">core-range (docs)</a>
  <a href="http://polymer.github.io/core-range/components/core-range/demo.html">(demo)</a> #29
- <a href="https://github.com/Polymer/core-sampler">core-sampler (GitHub repo)</a> (no docs) (no demo)
- core-scaffold (no docs) (no demo) #30
- <a href="http://polymer.github.io/core-docs/#core-selection">core-selection (docs)</a>
  <a href="http://polymer.github.io/core-selection/components/core-selection/demo.html">(demo)</a> #31
- <a href="http://polymer.github.io/core-docs/#core-selector">core-selector (docs)</a>
  <a href="http://polymer.github.io/core-selector/components/core-selector/demo.html">(demo)</a> #32
- core-shared-lib (no docs) (no demo) #33
- core-splitter (no docs) (no demo) #34
- core-theme-aware (no docs) (no demo) #35
- <a href="http://polymer.github.io/core-docs/#core-toolbar">core-toolbar (docs)</a>
  <a href="http://polymer.github.io/core-toolbar/components/core-toolbar/demo.html">(demo)</a> #36
- ~~<a href="http://polymer.github.io/core-docs/#core-tooltip">core-tooltip (docs)</a> (no demo) #1~~
- core-transition (no docs) (no demo) #37

The Polymer.js core-elements are updated regularily. If you notice that the list isn't up-to-date anymore please let me know.

Other suggestions about widgets or features you would like to have ported to Polymer.Dart are very welcome too.

**Comment by MikeMitterer** [comment]
Hi, here are my top 5:
- [x] core-layout-grid
- [ ] core-pages
- [ ] core-splitter
- [ ] core-overlay
- [ ] core-theme-aware

thx

Feature request: DI!!!!! would be great. The on that is used in AngularDart. I am really curious how this could be accomplished. I am sure its a bit a challenge but it would be cool to have it.

**Comment by zoechi** [comment]
Hi Mike,
thanks a lot for this info!
I would love to have DI-integration in Polymer too but I think this should be implemented on Polymer-level not element level.
I created an issue (with a link to a recent discussion about this topic).
https://code.google.com/p/dart/issues/detail?id=18875
